### ISSUE TITLE
Derive needs to be disabled on blank BCOs 

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal_userdb#289]
Derive button is present but apparently non-responsive 
```
ToolsDropDown.js:29 Uncaught TypeError: kv is not a function
    at Object.onClick (ToolsDropDown.js:29:14)
    at Object.onClick (useMenuItem.js:83:94)
    at Object.onClick (useButton.js:79:96)
    at useListItem.js:66:72
    at Object.We (react-dom.production.min.js:52:317)
    at Ge (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Pr (react-dom.production.min.js:100:68)
    at Or (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
onClick	@	ToolsDropDown.js:29
```

**Comment by tiwa1154** [comment]
What's the status on this? It's been a while
